name: Build and Dockerise UQMarks

on:
  pull_request:
    branches: ["master"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  js-build-and-format:
    runs-on: ubuntu-latest
    environment: preview
    defaults:
      run:
        working-directory: ./react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build npm bundle
        run: npm run build
        env:
          VITE_API_BASE_URL: https://www.uqmarks.com

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-uqmarks-vue-app
          path: react-app/dist

      - name: Run Prettier format check
        run: npm run format:check

      - name: Run TypeScript typecheck
        run: npm run typecheck

  docker-build:
    runs-on: ubuntu-latest
    environment: preview
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize image name to lowercase and set tag
        run: |
          LOWER_IMAGE_NAME=$(echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          echo "LOWER_IMAGE_NAME=$LOWER_IMAGE_NAME" >> $GITHUB_ENV

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "TAG=pr-${{ github.event.pull_request.number }}-build-${{ github.run_number }}" >> $GITHUB_ENV
          else
            echo "TAG=latest-build-${{ github.run_number }}" >> $GITHUB_ENV
          fi

          echo "Building image: $LOWER_IMAGE_NAME:$TAG"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.LOWER_IMAGE_NAME }}:${{ env.TAG }}

      # - name: Build Docker image
      #   run: |
      #     docker build -t "$LOWER_IMAGE_NAME:$TAG" .

      # - name: Save Docker image to tar
      #   run: |
      #     docker save "$LOWER_IMAGE_NAME:$TAG" -o uqmarks-image.tar

      # - name: Upload Docker image artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: uqmarks-docker-image
      #     path: uqmarks-image.tar
